// ----------------------
// ⚠️🚨  NOTE: All color palettes and exports *below* this comment line are the
//       current (new) color system and should be used in the codebase.
//       All color objects and exports *above* are deprecated and should be migrated away from. 🚨⚠️
// ----------------------

export const base = {
  // figma primitives neutral scale
  light: {
    base1: '#FFFFFF',
    base2: '#F2F2F2',
    base3: '#E5E5E5',
    base4: '#CCCCCC',
    base5: '#B2B2B2',
    base6: '#999999',
    base7: '#808080',
    base8: '#666666',
    base9: '#4D4D4D',
    base10: '#333333',
    base11: '#1A1A1A',
    base12: '#122023',
  },
  // figma primitives dark scale
  dark: {
    base1: '#0B1315',
    base2: '#0D1619',
    base3: '#0E1A1C',
    base4: '#101D20',
    base5: '#122023',
    base6: '#2A3639',
    base7: '#414D4F',
    base8: '#596365',
    base9: '#71797B',
    base10: '#898F91',
    base11: '#A1A5A7',
    base12: '#FFFFFF',
  },
};

export const brand = {
  light: {
    brand1: '#D9FEDC',
    brand2: '#B3FDB9',
    brand3: '#8CFD96',
    brand4: '#66FC73',
    brand5: '#40FB50',
    brand6: '#33C940',
    brand7: '#269730',
    brand8: '#1A6420',
    brand9: '#0D3210',
    brand10: '#0D3210',
    brand11: '#0D3210',
    brand12: '#0D3210',
  },
  dark: {
    brand1: '#0D3210',
    brand2: '#1A6420',
    brand3: '#269730',
    brand4: '#33C940',
    brand5: '#40FB50',
    brand6: '#66FC73',
    brand7: '#8CFD96',
    brand8: '#B3FDB9',
    brand9: '#D9FEDC',
    brand10: '#D9FEDC',
    brand11: '#D9FEDC',
    brand12: '#D9FEDC',
  },
};

export const error = {
  light: {
    error1: '#FFF0F3',
    error2: '#FFD9E0',
    error3: '#FFB3C1',
    error4: '#FF8DA2',
    error5: '#FF3D5C',
    error6: '#CC314A',
    error7: '#992537',
    error8: '#661925',
    error9: '#330D12',
    error10: '#330D12',
    error11: '#330D12',
    error12: '#330D12',
  },
  dark: {
    error1: '#330D12',
    error2: '#661925',
    error3: '#992537',
    error4: '#CC314A',
    error5: '#FF3D5C',
    error6: '#FF8DA2',
    error7: '#FFB3C1',
    error8: '#FFD9E0',
    error9: '#FFF0F3',
    error10: '#FFF0F3',
    error11: '#FFF0F3',
    error12: '#FFF0F3',
  },
};

export const layerTokens = {
  light: {
    layer1Background: base.light.base2,
    layer1BackgroundHover: base.light.base3,
    layer1BackgroundPress: base.light.base4,
    layer1BackgroundFocus: base.light.base2,
    layer1BackgroundDisabled: base.light.base2,
    layer1BorderColor: base.light.base2,
    layer1BorderColorHover: base.light.base5,
    layer1BorderColorPress: base.light.base3,
    layer1BorderColorFocus: '#269730',
    layer1BorderColorDisabled: base.light.base3,
    layer1PlaceholderColor: base.light.base6,
    layer1OutlineColor: '#269730',

    layer2Background: base.light.base1,
    layer2BackgroundHover: base.light.base2,
    layer2BackgroundPress: base.light.base3,
    layer2BackgroundFocus: base.light.base1,
    layer2BackgroundDisabled: base.light.base1,
    layer2BorderColor: base.light.base4,
    layer2BorderColorHover: base.light.base5,
    layer2BorderColorFocus: '#269730',
    layer2BorderColorPress: base.light.base4,
    layer2BorderColorDisabled: base.light.base3,
    layer2PlaceholderColor: base.light.base6,
    layer2OutlineColor: '#269730',

    layer3Background: base.light.base2,
    layer3BackgroundHover: base.light.base3,
    layer3BackgroundPress: base.light.base3,
    layer3BackgroundFocus: base.light.base2,
    layer3BackgroundDisabled: base.light.base2,
    layer3BorderColor: base.light.base4,
    layer3BorderColorHover: base.light.base4,
    layer3BorderColorFocus: '#269730',
    layer3BorderColorPress: base.light.base5,
    layer3BorderColorDisabled: base.light.base4,
    layer3PlaceholderColor: base.light.base6,
    layer3OutlineColor: '#269730',
  },
  dark: {
    layer1Background: base.dark.base3,
    layer1BackgroundHover: base.dark.base4,
    layer1BackgroundPress: base.dark.base2,
    layer1BackgroundFocus: base.dark.base3,
    layer1BackgroundDisabled: base.dark.base3,
    layer1BorderColor: base.dark.base3,
    layer1BorderColorHover: base.dark.base6,
    layer1BorderColorPress: base.dark.base4,
    layer1BorderColorFocus: '#40FB50',
    layer1BorderColorDisabled: base.dark.base4,
    layer1PlaceholderColor: '#999999',
    layer1OutlineColor: '#40FB50',

    layer2Background: base.dark.base5,
    layer2BackgroundHover: base.dark.base6,
    layer2BackgroundPress: base.dark.base4,
    layer2BackgroundFocus: base.dark.base5,
    layer2BackgroundDisabled: base.dark.base5,
    layer2BorderColor: base.dark.base7,
    layer2BorderColorHover: base.dark.base8,
    layer2BorderColorFocus: '#40FB50',
    layer2BorderColorPress: base.dark.base6,
    layer2BorderColorDisabled: base.dark.base6,
    layer2PlaceholderColor: '#999999',
    layer2OutlineColor: '#40FB50',

    layer3Background: base.dark.base6,
    layer3BackgroundHover: base.dark.base7,
    layer3BackgroundPress: base.dark.base5,
    layer3BackgroundFocus: base.dark.base6,
    layer3BackgroundDisabled: base.dark.base6,
    layer3BorderColor: base.dark.base7,
    layer3BorderColorHover: base.dark.base8,
    layer3BorderColorFocus: '#40FB50',
    layer3BorderColorPress: base.dark.base6,
    layer3BorderColorDisabled: base.dark.base7,
    layer3PlaceholderColor: '#999999',
    layer3OutlineColor: '#40FB50',
  },
};

export const brandTokens = {
  light: {
    brandBackground: brand.light.brand6,
    brandBackgroundHover: brand.light.brand7,
    brandBackgroundPress: brand.light.brand8,
    brandBackgroundFocus: brand.light.brand6,
    brandBackgroundDisabled: brand.light.brand2,
    brandColor: '#FFFFFF',
    brandColorPress: '#E5E5E5',
    brandColorDisabled: '#FFFFFF',
    brandBorderColor: brand.light.brand6,
    brandBorderColorHover: brand.light.brand7,
    brandBorderColorPress: brand.light.brand8,
    brandBorderColorFocus: brand.light.brand5,
    brandBorderColorDisabled: brand.light.brand2,
    brandPlaceholderColor: '#999999',
    brandOutlineColor: brand.light.brand5,
  },
  dark: {
    brandBackground: brand.dark.brand5,
    brandBackgroundHover: brand.dark.brand6,
    brandBackgroundPress: brand.dark.brand4,
    brandBackgroundFocus: brand.dark.brand5,
    brandBackgroundDisabled: brand.dark.brand1,
    brandColor: '#122023',
    brandColorPress: '#2A3639',
    brandColorDisabled: '#414D4F',
    brandBorderColor: brand.dark.brand5,
    brandBorderColorHover: brand.dark.brand6,
    brandBorderColorPress: brand.dark.brand4,
    brandBorderColorFocus: brand.dark.brand6,
    brandBorderColorDisabled: brand.dark.brand1,
    brandPlaceholderColor: '#999999',
    brandOutlineColor: brand.dark.brand6,
  },
};

export const content = {
  light: {
    contentPrimary: '#1A1A1A',
    contentSecondary: '#808080',
    contentTertiary: '#CCCCCC',
    contentBrand: '#33C940',
    contentBrandHover: '#269730',
    contentBrandPress: '#1A6420',
  },
  dark: {
    contentPrimary: '#FFFFFF',
    contentSecondary: '#999999',
    contentTertiary: '#4D4D4D',
    contentBrand: '#40FB50',
    contentBrandHover: '#66FC73',
    contentBrandPress: '#33C940',
  },
};
